### ISSUE TITLE
KeyError: "[E002] Can't find factory for 'pytt_wordpiecer'.

### ISSUE THREAD

**Issue by Aya-S** [huggingface/neuralcoref#192]
```
import en_pytt_bertbaseuncased_lg
nlp = en_pytt_bertbaseuncased_lg.load()
```
produces this error 
KeyError: "[E002] Can't find factory for 'pytt_wordpiecer'. This usually happens when spaCy calls `nlp.create_pipe` with a component name that's not built in - for example, when constructing the pipeline from a model's meta.json. If you're using a custom component, you can write to `Language.factories['pytt_wordpiecer']` or remove it from the model meta and add it via `nlp.add_pipe` instead."

**Comment by svlandeg** [comment]
Hi @Aya-S : this seems related to [spaCy's en_pytt_bertbaseuncased_lg model ](https://spacy.io/models/en#en_pytt_bertbaseuncased_lg )rather than to the neuralcoref plugin?

I will close it here but feel free to open an issue on the [spaCy issue tracker](https://github.com/explosion/spaCy/issues). When you do, make sure to include the details of your environment by pasting the output of `python -m spacy info --markdown`
