### ISSUE TITLE
Integration of different word embeddings for prediction 

### ISSUE THREAD

**Issue by masonedmison** [huggingface/neuralcoref#228]
HI,

I am using SciSpacy with neuralcoref (by adding `ENTITY` to `ACCEPTED_ENTS`) and would also like to use the SciSpacy word vectors if possible. 

I already have switched the `self.static_vectors` and `self.tuned_vectors` to point to the `self.vocab.vectors` in the `NeuralCoref` constructor. I also changed `SIZE_EMBEDDING` constant to 300 dims (the dimensions of the SciSpacy vectors). 

After these changes I am running into shape conflicts within the `thinc` module. 

This said I have three questions:
- Being that I am working with biomedical text, would you think using domain-specific would improve performance since I would only be using them during prediction rather than training?

- Is there a better way to integrate these embeddings than what I am currently doing?

- If I am on the right path of integrating these embeddings, could you perhaps point me to a resource or give me an idea of how to adjust sizes in the ```# A BUNCH OF SIZES #``` section to accept my embeddings with 300 dimension?

Please let me know if I can provide any more information.

Thanks in advance and for making this very awesome tool :)

**Comment by svlandeg** [comment]
Hi @masonedmison, apologies for following up a bit late (and please ignore the bot). We have actually been working on a whole new release of thinc (cf. https://thinc.ai/) which should make debugging/resolving shape issues much easier. Additionally, we're now working towards the v.3 release of spaCy that will use the new thinc and its configuration files, so that it should become much easier to support use-cases like yours. Finally, we hope to fully integrate neuralcoref into spaCy, so that it will all work together much more flawlessly. Unfortunately all of this is taking a bit of time.

I do think that it could be beneficial for your use-case to take advantage of the SciSpacy word vectors. But it probably only makes sense to do so, if you also [retrain](https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/train/training.md) the coref model on them. But then you'd probably also need a coref-annotated dataset for the biomedical domain?
