### ISSUE TITLE
Inconsistent Cluster Behavior Between Doc and Span

### ISSUE THREAD

**Issue by eric-yates** [huggingface/neuralcoref#65]
MacOS High Sierra (10.13.3)
spacy == 2.0.11
neuralcoref == 3.0
en-coref-md == 3.0.0

Hi, I'm working to resolve coreferences within a single sentence that is part of a larger paragraph. For example, in the short paragraph:

```
nlp = spacy.load('en_coref_md')

tokens = nlp("Carol bought a new book. As Carol read, she learned.")

print(tokens._.coref_clusters)

for n, s in enumerate(tokens.sents):
    print(s._.coref_cluster)
```

The first print yields: [Carol: [Carol, Carol, she]]
The second print yields (for both s in tokens): None

Why does neuralcoref not work within a Span here? I don't want coreferences between sentences, only within a single sentence. For example, I do not want 'Carol' in the first sentence to corefer to either 'Carol' or 'she' in the next sentence. However, I need to run the Doc object at the paragraph level to be able to tell what the sentences are.

I suppose a better question may be: Is it possible for neuralcoref to only find coreferences inside a single sentence?

**Comment by eric-yates** [comment]
I figured out a way to only check for coreference in a sentence, although it seems a bit hacky. For example in:

```
[Carol: [Carol, she]]
```

I first calculated the begin index and the end index of the sentence in question. Then, I checked to see if the index of the first mention (Carol) was in between the begin index and end index. 

If it was, then it was a valid coreference within a sentence. If it was not, then it was a coreference from another sentence.

Is there a better approach than this?

**Comment by thomwolf** [comment]
Well the behavior in your first comment is intended:
- if you ask for the coreference of a Doc, you get all the coreferences.
- if you ask for the coreference of a Span you only get coreferences that matches exactly the Span.
This is required to navigate easily within the chains. I understand it may be a bit surprising, I will try to clarify it a bit in the readme.

Regarding your second comment, another way to limit coreference to single sentences only would be to split your string in sentences (like `string.split('.')`) and feed a list of strings instead of a single string to the `nlp` object.

**Comment by eric-yates** [comment]
Ah I see, thank you for the clarification. We're relying on user input that may put in decimal numbers, abbreviations, etc. that would mess up the split string method. I tried first passing the whole paragraph through `nlp` and then passing each sentence in doc.sents through `nlp`, although I found that performance was too slow for our requirements

A coreference option within a sentence could be a useful feature for the future. Until then, the workaround I made above works (if a bit hacky) for anyone looking to do this
