### ISSUE TITLE
In what sense state of the art?

### ISSUE THREAD

**Issue by matanster** [huggingface/neuralcoref#87]
This leaves a terrific impression, but how did you conclude this is state of the art? I think this should be noted in some prominent way, even if it is already there in the blog post!

**Comment by ljinstat** [comment]
The neuralcoref model is inspired by the mention-ranking model which is implemented in previous the state-of-the-art papers (mentioned in the blog and issue #71).
Due to the expectation of relatively good performance and easier implementation, the neuralcoref model isn't actually implemented the same as it is mentioned in those two papers. Thus, it loses some performance without surprise. Besides, these two papers are not any more the state-of-the-art (replaced by the end-to-end neural coreference model). 
It depends on how you define "the-state-of-the-art". As we know, it is tough to improve the performance of the coreference model a lot. Despite of the gap between the neuralcoref model and the current best model, this neuralcoref model is great for inference though.

**Comment by thomwolf** [comment]
You are right, it's not state-of-the-art anymore.
The AllenAI system is.
I will change the wording.
