### ISSUE TITLE
Scores between the mentions

### ISSUE THREAD

**Issue by sanjanalreddy** [huggingface/neuralcoref#92]
I am trying to get the scores which are shown on the neuralcoref viz but don't seem to be able to do so. I tried to call `doc._.coref_scores` but it mentions that the extension has not been set. Has anyone been able to get the scores?

**Comment by devitoclic** [comment]
I'm having the same issue right now. Some coreferences are not resolved because the corefs scores are too low.
It would be great to set a threshold to force the coref resolution.
I saw `doc._.coref_scores` from 3.0.0 but i cannot use it since it's not released as a spacy package yet.
Do you have any news about this feature ?

**Comment by SanjanaLokesh** [comment]
Looked a little more into this issue. Looks like the code to get the coreference scores is there, but the models have to be retrained. So one of the solutions is to pull the latest version of master and then follow the instructions to retrain the models. Doing so, will enable the extension `doc._.coref_scores`.

**Comment by thomwolf** [comment]
The latest release (4.0) now outputs coreference scores.
