### ISSUE TITLE
Repeated replacement of corefering mention by main mention

### ISSUE THREAD

**Issue by selvaganeshmuthu** [huggingface/neuralcoref#96]
I am trying to find coreference between consecutive questions. I can have sentences that have coreference relation or not and replacement should be done only for sentences with coreference relation. I have the following questions,
1. how to view old Issue.
2. how to add new Issue?

I try to find the coreference resolved text the following way.

```
import en_coref_lg


coref = en_coref_lg.load()

text = 'how to view old Issue. how to add new Issue?'
doc = coref(text)
resolved = doc._.coref_resolved
print(doc._.has_coref)
print(doc._.coref_clusters)
print(resolved)
```
**Output:**
> True
[old Issue: [old Issue, new Issue, Issue]]
how to view old Issue. how to add old Issueold Issue?

Excepted Result for coref resolved is "how to view old Issue. how to add new issue?" or "how to view old Issue. how to add old issue?".

 I assume during the replace process of corefering mention by the main mention is done twice. Is this the excepted behaviour?

**Comment by thomwolf** [comment]
Hi, yes I think this is the expected behavior. You can compute you own resolved string from the coreference cluster and the string if you want a different behavior.

Here is the current function that compute the `coref_resolved` string for inspiration: https://github.com/huggingface/neuralcoref/blob/master/neuralcoref/neuralcoref.pyx#L262
